name: GMGWebsite
version: 1.0.0
author: Matthew French
description: A sample web application
homepage: http://gamemakersgarage.com
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  crypto: '>=0.9.0 <0.10.0'
  three:
    path: ../three/
  unittest: '>=0.11.4 <0.12.0'
  vector_math: any
dev_dependencies:
  animation: any
transformers:
- $dart2js:
    minify: true