version: '3.9'
name: 'forum-server-local'
services:
  forum-db-node1:
    image: scylladb/scylla:5.2.15
    restart: unless-stopped
    container_name: forum-db-node1
    user: root
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        echo 1048576 > /proc/sys/fs/aio-max-nr
        /docker-entrypoint.py --seeds=forum-db-node1 --smp 1 --memory 4G --overprovisioned 1 --api-address 0.0.0.0 --developer-mode 1 --reactor-backend=epoll
    security_opt:
      - seccomp:unconfined
    privileged: true
    ports:
      - "9042:9042"
    #environment:
    # Where our data will be persisted
    volumes:
      - "forum-db-local:/var/lib/scylla"
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties"
      - "./scylla/scylla-server.conf:/etc/supervisord.conf.d/scylla-server.conf"
volumes:
  forum-db-local: