version: '3.9'
name: 'forum-server'
services:
  forum-db-node1:
    image: scylladb/scylla:5.2.15
    restart: unless-stopped
    container_name: forum-db-node1
    user: root
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        echo 1048576 > /proc/sys/fs/aio-max-nr
        /docker-entrypoint.py --seeds=forum-db-node1 --smp 1 --memory 4G --overprovisioned 1 --api-address 0.0.0.0 --developer-mode 0 --reactor-backend=epoll
    security_opt:
      - seccomp:unconfined
    privileged: true
    #environment:
    # Where our data will be persisted
    volumes:
      - "forum-db:/var/lib/scylla"
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties"
      - "./scylla/scylla-server.conf:/etc/supervisord.conf.d/scylla-server.conf"
  forum-server:
    # Build the image from the dockerfile if it does not already exist
    build:
      context: ./
      dockerfile: forum-server.Dockerfile
    image: forum-server
    container_name: forum-server
    restart: unless-stopped
    # Assume we have generated valid certificates at this location to pull in
    volumes:
      - "C:/letsencrypt/etc/archive/server.matthewfrench.io:/certs"
    ports:
      - '7779:7779'
    expose:
      - '7779'
volumes:
  forum-db: