version: '3.9'
name: 'forum-server'
services:
  forum-server:
    # Build the image from the dockerfile if it does not already exist
    build:
      context: ./
      dockerfile: forum-server.Dockerfile
    image: forum-server
    container_name: forum-server
    restart: unless-stopped
    # Assume we have generated valid certificates at this location to pull in
    volumes:
      - "C:/letsencrypt/etc/archive/server.matthewfrench.io:/certs"
    ports:
      - '7779:7779'
    expose:
      - '7779'